component_depth: 5
languages:
  - name: typescript
    production:
      exclude:
        - /src/__test__/.*\.tsx
        - /src/serviceWorker.ts
        - /src/setupTests.ts
    test:
      include:
        - /src/__test__/.*\.tsx