language: node_js
node_js:
  - '12'
deploy:
  provider: firebase
  token:
    secure: "VliZqs+17Jr5x3wKkrN3tnWEdGzjK9B2dhqPkYGXV7WgLIe9lc8tXUnOgzkqb5ohghAYrLIlA/Ni4L9RJVZDlJCPGRZ4P8DSQBIdsXQeGBUcYr7iQhHxBjVRWzHJcjxup4NftBCtdcP6z/DGlz6q3F7DhRo+g4g2Ws5XC3/YNVtlvJngEYnjvTuj8XRHglzpk4ZeZqO5Ta/n1ImkUwAUlsugiuj3um208KJyswHc4n0xqlpVjc+Jbzm2eVQ0XIGLF/2zgaORk0HQ0B1rvwIaSNrCDW/ssR18aL866WKbpKrPzigcJsjYRX2v5DI/GyAHIPMhPp4+WAbcCEoTGaHLsS3WUmvYHpU6D+/m/6OMjbdpchtM8U5/qqWl1JFy+c1zMu4YOnDT7MaYHzDNVljw12+x3UTjad/t3dykpeiSKuR8m1AGmF5+KDrePyLzPjTgfHGJJrmP/hG95x5c96CKX7dZiE3VMZvDlkQ1MlOlALMTIXntE7mKMzSuJCznV5GyT0k2KZIOB/VB/BtDmv3aa5M24kD1sUEOKhpQ+LTVraQ9li/9YceurSejOYfwerMWPhWbIBnPSlZB72LI/1uzkM0E7nMzmfTYbG0w4gCORkgnJDMjemnmTGcr8l9wliWOTA/Xpnl1C4Uq0i7yyYKwUM4gG6x2gayePnAX6erIu6U="
