language: node_js
node_js:
  - '14'
install:
  - npm ci
script:
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: Umx93MjO7QEVopJ1wD96APMW0mnlRDqouVkLw8VoXBI/lOG1uUV0Bfhbj2ogs2EM2UzDg/vEBrnx0ztwMNyc6pZ2Nc/9+7lHz6ZIk5TY3cj4XuV2+KvnNygZ6Oulph8Upe3BlOpUbMJgzPtu/y0t6vX4SHWuq6ceIftkpJEPR9dBZ8U3+x3bouxpB4oI8P/trOQH2e4njCLcZEU0TRJaaKnooATNqUYR6mu1ftxoyYXMJQRcTYItdq9YPUGwoyNVhL7KCpdrqeSwW+WVWEKjWxZ7XHYncCbqj/hRcPLBi0OrVFXrMTUUr5sNDwt+ipBbmAmHBz4XL/4VCpCwQlin82vF7r+Zef5PIiamKY5xsYw6/YK4qItvdsH9xeXSC9azkZt3XIaibH6AcsRv9OGUx0qyr/mzBii37iZ1cOL5DbZBE2NATts3RaQyjAfM/jqhSOON3HAce62VHb2qvgVNepiWhXDR3L/rOwzRn75nzh6aY5eaJ//pmkBbMf6n1bVMByFQ5KTzdoXQgatpmWBePCjWoQ8qc2OZ/tngPn8AbFo+n+R5SlgBoSws8Vuvj5zL3cR1nbe9cRJ9LIvQ3JCFgWNEAQ8CPB74+EDwJpnHdPLLG7mosudQJwVFK6hiXQm97ZdGBrkR98q0CMTsnDrM6T5ysmH2RU6u5yhiCWmVZSM=
  on:
    branch: master
notifications:
  slack:
    secure: kSFDYtD+vhkhobO1xb0mGI0y2AuZtdsmBTe+NMzBk7QiQRtKhhv0HGz3RH4UrgfiWZ3ZDW4gme+gJg9EU2fobu/wcOzFLA4SrM1M2xcpzmjbNXdgv5wru0ff/DAJXHnEj6B7PRNz4ukGV3M4vWvOW45/F1R7uGjMEFu4MXOiwtRAlVaFjgJCM12nb2c5O0lzTlccKftC8SzxFGInrz7FRWF7gmdXfTTYc4ApkwvMPKIPU3COMXv3Mg463uUIyNBsHJ3eeriFJp0j6ZURLSzKuK5i/Kx/E/z5tMzbtc4n1X7tUlsz8K+wlY7DxKzZSW1jg70fjW+rQ7PStqC3Bohta9V6+lXyF+qtgwdbz+MEq5ZsCOu+q01Se6uM/l6ixBHxiBACmcv5nsHL8WOOqiyKjju52ypwxfQC7qOPaSgVlRilgFb7wU5eGic407VnmRWgrpTxWehy2qCchCE5bO+SWm5YYi/TxZbzEtjD7o547dlszGwsc80IlGyxW1wD36tuJ70FsLVZbUiiYqLcR/iAK2W3eTN1K1IwjcYvskvWdYlqJB/AT3ywpJ3PiJ1FKYT0tDGoD+Xztw/P/WFlSRLd5xQgcWbcig23qC+TgA4KjMTzpVM8BU41O9U+GxQDpAGLueKL38qQOl+BVS6lULGO4x4+zdAbboqCAg2beuR/YSo=
