language: node_js
node_js:
  - '12'
install:
  - npm install
script:
  - npm test
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: JpEyM+TCXZIsT8QhLeuN3L8AzZJ0LH7Fa9+D/JjaejBFS4lHLDkohzWdyag+YEjPviogaGM8dvs4yjC9quA5YXRuIXUFVbzsNoCkVtq2/NEofxF+GQQu7Ktlx/el1S1B3jjtT7EPJbfQnZcjmdS3LiNHYilT5A+SPEh2N+JCRpBdi8ZExibkur8Fvywr/2hq27UxBpGBPyKWvWltkThgVd9K3PgF89MFlSjgwV3zm0+zC4OtWaRGyIHfYALe3j42zK2kF71etPP1FkK8c4hFsookev2CvDkBN7knzRiWpktfVqo6FMWv/Gjqso8A6nUWo0fmDd6cyB5XNrw9uhc7i4PkrfmlRNOFL4Us35pjvJZbYL8AGPyNjEmyqIcynWy+FAN/KNe+ni1bqGg6pz3PtPFNHIo1GzfCMk0F5MdJikFlhCYJx6ICZY3C/fDaz6vBr2W1Q6fyjZjvbtCn/PZO2/mL1eLYfCK23bIABs8lLoLAMqg1+kUoFhimfkF/LEoc2xeYouonFxJzy9ArxmcNAGp9Vi88k/5GIe8EyUVUy8KhFOoqSm0wi6ugLENj614ZyUPP53iB3mAeLTF4SLfCNT0fmUMWZOV+DCk0pOBzaZl5L6zPuiPichueCLPHaVYZS/iGrtTggGxOkpGW78Z72YiIKCp2yafUbKENLJHPZ5M=
  on:
    branch: master
notifications:
  slack:
    secure: kSFDYtD+vhkhobO1xb0mGI0y2AuZtdsmBTe+NMzBk7QiQRtKhhv0HGz3RH4UrgfiWZ3ZDW4gme+gJg9EU2fobu/wcOzFLA4SrM1M2xcpzmjbNXdgv5wru0ff/DAJXHnEj6B7PRNz4ukGV3M4vWvOW45/F1R7uGjMEFu4MXOiwtRAlVaFjgJCM12nb2c5O0lzTlccKftC8SzxFGInrz7FRWF7gmdXfTTYc4ApkwvMPKIPU3COMXv3Mg463uUIyNBsHJ3eeriFJp0j6ZURLSzKuK5i/Kx/E/z5tMzbtc4n1X7tUlsz8K+wlY7DxKzZSW1jg70fjW+rQ7PStqC3Bohta9V6+lXyF+qtgwdbz+MEq5ZsCOu+q01Se6uM/l6ixBHxiBACmcv5nsHL8WOOqiyKjju52ypwxfQC7qOPaSgVlRilgFb7wU5eGic407VnmRWgrpTxWehy2qCchCE5bO+SWm5YYi/TxZbzEtjD7o547dlszGwsc80IlGyxW1wD36tuJ70FsLVZbUiiYqLcR/iAK2W3eTN1K1IwjcYvskvWdYlqJB/AT3ywpJ3PiJ1FKYT0tDGoD+Xztw/P/WFlSRLd5xQgcWbcig23qC+TgA4KjMTzpVM8BU41O9U+GxQDpAGLueKL38qQOl+BVS6lULGO4x4+zdAbboqCAg2beuR/YSo=