version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install:
          node-version: '14' 
      - node/install-packages
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c8:33:f9:bb:85:47:cc:8f:77:07:f3:4a:74:34:0f:a9"
      - run: ssh -p 49568 web-admin@xg41.ukitomato.dev 'cd /usr/share/nginx/html && git pull && exit'


workflows:
  build-and-deploy:
    jobs:
       - build:
          filters:
            branches:
              only: master
#      - deploy:
#          requires:
#            - build-and-test
#          filters:
#            branches:
#              only: master
