version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run build
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b0:a5:e1:b0:dd:09:20:4b:34:25:13:90:f6:95:9c:2a"
      - run: ssh -p 49568 web-admin@ukitomato.codes 'cd /var/www/portfolio && git pull'

workflows:
  build-and-test-and-deploy:
    jobs:
      - build-and-test
      - deploy
        requires:
          - build-and-test
        filters:
          branches:
            only: master